language: python
cache: pip
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
    - "pypy"
    - "pypy3"
install:
    - pip install -r requirements.txt
script:
    - make test
after_success:
    - codecov
